### ISSUE TITLE
AsyncStorage deprecation warning.

### ISSUE THREAD

**Issue by jckw** [morrys/wora#10]
When using this package in React Native (via `react-relay-offline`), there are warnings shown about using AsyncStorage from react-native as opposed to @react-native-community/async-storage. 

```
Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage
```

Importing from both react-native and @react-native-community/async-storage [creates a race condition between the packages](https://github.com/react-native-community/async-storage/issues/12#issuecomment-526068090) which can cause hard to debug issues.

This could probably be resolved fairly easily by changing the dependencies to include @react-native-community/async-storage and the storage.native.ts file.

**Comment by morrys** [comment]
I agree with what you say, but this is a breaking change.

Perhaps it is also necessary to add the possibility of using the react-native AsyncStorage in this way:

```ts
import Cache, { CacheStorage, CacheOptions } from "@wora/cache-persist";
import AsyncStorage from '@wora/cache-persist/lib/deprecated/asyncstorage';


const asyncOptions : CacheOptions = {
        storage: AsyncStorage,
    }

const cacheAsync = new Cache(asyncOptions);
```

What do you think?

**Comment by jckw** [comment]
So the default would be the now deprecated AsyncStorage from React Native and using @react-native-community/async-storage would require passing options?

I think that seems okay, but given that AsyncStorage from react-native is being deprecated and can actually break applications I wouldn't mind seeing a breaking change and a version bump either.

**Comment by morrys** [comment]
Both options are correct, I don't mind putting the community version as default.

We'll make a decision by the weekend and I'll release it :)

**Comment by morrys** [comment]
continue here https://github.com/morrys/wora/issues/11
