### ISSUE TITLE
ApolloClient

### ISSUE THREAD

**Issue by pranavbabu** [morrys/wora#13]
It seems like your instance of ApolloClient doesn't support local state management.

**Comment by morrys** [comment]
Hi @pranavbabu,
strange, I have extended the functionality of Apollo Client. It should support it.
Can you give me some more information or an example that highlights this problem?

**Comment by pranavbabu** [comment]
here is my example, I use your library in React Native:
```const cache = new ApolloCache(cacheOptions);
const client = new ApolloClient(
  {
    link: ApolloLink.from([errorLink, requestLink, batchLink]),
    cache,
    resolvers: {},
  },
  offlineOptions
);

cache.writeData({
  data: {
    someField: [],
  },
});

export default client;```

after that when I'm trying to get this local field in code, it returns empty data field and Apollo Devtools also shows that there is no such field in cache, I've also tried to add typeDefs, but it didn't work.

**Comment by morrys** [comment]
Is this problem only present when using the offline library? Are you also using wora/apollo-cache?

It would be useful if you can do the [fork of this project](https://github.com/morrys/offline-examples/tree/master/apollo/todo) and recreate the problem, so that over the weekend I can take a look :)

**Comment by pranavbabu** [comment]
I've tried to reproduce it on your example of web app. It works fine (not showing in apollo devtools) but at least I can get data and show it in the DOM, maybe this issue related only for React Native....

**Comment by morrys** [comment]
really strange ... difficult to answer with this information. Can you create a simple example on react-native that highlights the error? otherwise I hope I have time this weekend to create it.

**Comment by pranavbabu** [comment]
I'll be possible to do this only on next week

**Comment by morrys** [comment]
Hi @pranavbabu,
today I quickly created an example project for apollo in [react-native](https://github.com/morrys/offline-examples#react-native-1)

Surely it needs some refactor but it is enough to be able to recreate your problem :)

I'm waiting for your news.

Lorenzo

**Comment by pranavbabu** [comment]
Hi, @morrys here is example with not working local state management https://github.com/pranavbabu/offline-examples/tree/test/local-state

**Comment by morrys** [comment]
hi @pranavbabu, sorry if I answer only now, but I'm trying to fix the last things before going on vacation :) (from 11 to 16 September)

This must be done after the cache has been rehydrated:
https://github.com/pranavbabu/offline-examples/blob/test/local-state/apollo/react-native/todo/src/App.tsx#L55-L64

try and if you have problems tell me well :)

**Comment by pranavbabu** [comment]
@morrys It works!

**Comment by morrys** [comment]
well then i can close the issue and confirm that local state management is supported.
