### ISSUE TITLE
Upcoming changes in offline-first, relay-offline and apollo-offline

### ISSUE THREAD

**Issue by morrys** [morrys/wora#14]
**Add more parameters in the callback functions in the offline workflow**
These changes make it easier to extend the offline workflow

### callback functions to be modified
  * execute: (offlineRecord: OfflineRecordCache<T>) => Promise<any>,
  * finish?: (success: boolean, mutations: ReadonlyArray<OfflineRecordCache<T>> ) => void,
  * onComplete?: (options: { offlineRecord: OfflineRecordCache<T>, response: any }) => boolean;
  * onDiscard?: (options: { offlineRecord: OfflineRecordCache<T>, error: any }) => boolean;
  * onPublish?: ( offlineRecord: OfflineRecordCache<T>) => OfflineRecordCache<T>,

### libraries to be modified
* wora/offline-first
  * add the store parameter set with the storeOffline
  * consider adding two new callback functions: start, preExecute
* wora/apollo-offline
  * add the client parameter set with the apollo client
* wora/relay-offline
  * add the client parameter set with the relay environment

**Comment by pranavbabu** [comment]
Can I get a list of queries from the queue somewhere inside the app ?

**Comment by morrys** [comment]
This is already possible:
* **offline-first**: store.getListMutation()
* **Apollo**: client.getStoreOffline().getListMutation()
* **Relay**: environment.getStoreOffline().getListMutation()

You can also use the storeOffline subscription to be notified when the queue is changed.
* **offline-first**: store.subscribe(callback)
* **Apollo**: client.getStoreOffline().subscribe(callback)
* **Relay**: environment.getStoreOffline().subscribe(callback)

In the version 2.0.0 of cache-persist I am considering to change the interface of the callback so I advise you to follow these issues so as to be updated for any breaking changes :)

I will include this information in the documentation.

**Comment by pranavbabu** [comment]
Thank, a lot, the docs will help ;)

**Comment by morrys** [comment]
# offline-first

new offline-first options:
```
export type OfflineFirstOptions<T> = {
    manualExecution?: boolean;
    execute: (offlineRecord: OfflineRecordCache<T>) => Promise<any>;
    start?: (mutations: ReadonlyArray<OfflineRecordCache<T>>) => Promise<void>;
    finish?: (mutations: ReadonlyArray<OfflineRecordCache<T>>, error?: Error) => Promise<void>;
    onExecute?: (mutation: OfflineRecordCache<T>) => Promise<OfflineRecordCache<T>>;
    onComplete?: (options: { offlineRecord: OfflineRecordCache<T>; response: any }) => Promise<boolean>;
    onDiscard?: (options: { offlineRecord: OfflineRecordCache<T>; error: any }) => Promise<boolean>;
    onPublish?: (offlineRecord: OfflineRecordCache<T>) => Promise<OfflineRecordCache<T>>;
    compare?: (v1: OfflineRecordCache<T>, v2: OfflineRecordCache<T>) => number;
    // onDispatch?: (request: any) => any;
};
```
   * added setOfflineOptions
   * added start & onExecute options
   * removed offlineOptions in constructor
   * renamed restore function in hydrate
   * changed all return options function in promises
   * changed finish options, before: finish(isSuccess, mutations) after: finish(mutations, error)
   * code optimization

# apollo-offline
   * renamed hydrated function in hydrate
   * added setOfflineOptions
   * removed offlineOptions in constructor
   * update dependency offline-first with new options
   * optimization in saving backup data within the offline mutation. Only the modified elements are saved in the backup property.

```ts
import { ApolloClient } from "@wora/apollo-offline";
import { HttpLink } from "apollo-link-http";
import ApolloCache from '@wora/apollo-cache';

const httpLink = new HttpLink({
  uri: "http://localhost:4000/graphql"
});

const httpLinkOffline = new HttpLink({
  uri: "http://localhost:4000/graphql"
});

const client = new ApolloClient({
  link: httpLink,
  cache: new ApolloCache({
    dataIdFromObject: o => o.id
  })
});
client.setOfflineOptions({
  manualExecution: false, //optional
  link: httpLinkOffline, //optional
  start: async (mutations) => { //optional
    console.log("start offline", mutations)
  },
  finish: async (mutations, error) => { //optional
    console.log("finish offline", error, mutations)
  },
  onExecute: async (mutation) => => { //optional
    console.log("onExecute offline", mutation)
    return mutation;
  },
  onComplete: async (options ) => { //optional
    console.log("onComplete offline", options)
    return true;
  },
  onDiscard: async ( options ) => { //optional
    console.log("onDiscard offline", options)
    return true;
  },
  onPublish: async (offlinePayload) => { //optional
    console.log("offlinePayload", offlinePayload)
    return offlinePayload
  }
};)


// await before instantiating Query, else queries might run before the cache is persisted, TODO ApolloProviderOffline
await client.hydrate(): Promise<boolean>
```

# relay-offline
   * renamed restore function in hydrate
   * added setOfflineOptions
   * removed offlineOptions in constructor
   * removed isRestored function, now exist only isRehydrated
   * update dependency offline-first with new options
   * removed: automatic rollback management of the single failed mutation in the store (relay v6 & v7 no longer allows such integration)

```ts
import { Network } from "relay-runtime";
import { RecordSource, Store, Environment } from "react-relay-offline";

const network = Network.create(fetchQuery);

const networkOffline = Network.create(fetchQueryOffline);
const manualExecution = false;

const recordSource = new RecordSource();
const store = new Store(recordSource);
const environment = new Environment({ network, store });
environment.setOfflineOptions({
  manualExecution, //optional
  network: networkOffline, //optional
  start: async (mutations) => { //optional
    console.log("start offline", mutations)
  },
  finish: async (mutations, error) => { //optional
    console.log("finish offline", error, mutations)
  },
  onExecute: async (mutation) => => { //optional
    console.log("onExecute offline", mutation)
    return mutation;
  },
  onComplete: async (options ) => { //optional
    console.log("onComplete offline", options)
    return true;
  },
  onDiscard: async ( options ) => { //optional
    console.log("onDiscard offline", options)
    return true;
  },
  onPublish: async (offlinePayload) => { //optional
    console.log("offlinePayload", offlinePayload)
    return offlinePayload
  }
});
```

# apollo-cache
   * renamed hydrated function in hydrate
# relay-store
   * renamed restore function in hydrate
