### ISSUE TITLE
Removing stored mutations by query?

### ISSUE THREAD

**Issue by mattjennings** [morrys/wora#20]
Is there a way to remove stored mutations by query? For example, if a document is saved twice offline, I'd like to only send the last mutation when they go online. This means I would remove the prior mutations for that query when a new save is made.

I see that I can get the list of stored mutations via `client.getStoreOffline().getListMutation()`, but I want to find the ones that are using the same mutation query. Would something like `readMutations()` that follows a similar API to an Apollo cache's `readQuery()` make sense?

```js
// returns filtered list from client.getStoreOffline().getListMutation()
const mutations = client.getStoreOffline().getMutations({
  query: SAVE_DOCUMENT,
  variables: { id: documentId }
})

// run client.getStoreOffline().remove(id) for each result
```

or

```js
// removes mutations matching query
client.getStoreOffline().removeMutations({
  query: SAVE_DOCUMENT,
  variables: { id: documentId }
})
```

**Comment by morrys** [comment]
Hi @mattjennings,
as you could see the offline store is a store different from the apollo managed cache. The wora / offline-first library handles mutations in an array, this to be used not only in GraphQL contexts.

To solve your problem you could use getListMutation () to filter out mutations and then delete the ones you think are necessary. You might also consider adding data to the offline payload in the offline option 
```
onPublish: (offlinePayload) => {
offlinePayload.request.mydata = {
  ...
}
return offlinePayload;
}
```

to simplify the search in getListMutation ().

**Comment by mattjennings** [comment]
Ahh, thanks for the suggestion! I gave it a go, but ended up going with this approach instead:

When I make the mutation, I pass in a variable of `__mutation_id__` that isn't used in the query:

```js
// using @apollo/react-hooks
const [save] = useMutation(SAVE_TODO)

save({
  variables: {
    input,
    __mutation_id__: 'save-todo-item'  // not used by the query but will be kept in the offline mutation
   }
})
```

and then I made a function to search & remove those stored queries by said `__mutation_id__`

```ts
export function removeStoredMutationsById(id: string, options: { before?: number } = {}) {
  const storedMutationIds = client
    .getStoreOffline()
    .getListMutation()
    .filter(mutation => {
      const mutationId = mutation.request.payload.variables.__mutation_id__
      const isMatchingId = mutationId === id

      // only removes mutations before the passed in options.before (if provided)
      const isBefore = !options.before || mutation.fetchTime < options.before

      return isMatchingId && isBefore
    })
    .map(mutation => mutation.id)

  storedMutationIds.forEach(mutationId => {
    client.getStoreOffline().remove(mutationId)
  })
}
```

so in the end it looks something like

```js
// using @apollo/react-hooks
const [save] = useMutation(SAVE_TODO)

// time of this save so we can remove anything before it
const timeOfSave = Date.now()

await save({
  variables: {
    input,
    __mutation_id__: 'save-todo-item'  // not used by the query but will be kept in the offline mutation
   }
})

// save was successful
removeStoredMutationsById('save-todo-item', { before: timeOfSave })
```

from my brief usage of this approach it seems to accomplish what I was looking for.

**Comment by morrys** [comment]
For these operations I suggest using the  context object of the mutation.

```
save ({
   variables: {
     input
    },
context: {
     input,
     __mutation_id__: 'save-todo-item' // not used by the query but will be kept in the offline mutation
    }
})
```

and then recover the context
const mutationId = mutation.request.payload.context .__ mutation_id__

**Comment by mattjennings** [comment]
oh that is much better, I will update my comment to do it that way instead.

**Comment by morrys** [comment]
thanks to you who share problems and solutions :)
