### ISSUE TITLE
ApolloClientIDB is not passing all cache-persist options

### ISSUE THREAD

**Issue by mattjennings** [morrys/wora#22]
Is there a reason that ApolloClientIDB is only passing on the `serialize` and `persist` options for cache-persist? I'd like to use the `mutateKeys` option specifically

https://github.com/morrys/wora/blob/441516bcda13f351bcaa930de353565cfda32ccb/packages/apollo-offline/src/ApolloClientIDB.ts#L19-L43

**Comment by morrys** [comment]
hi @mattjennings,
you're absolutely right :) I thought I had it instead I did it only in relay ...
By weekend I'm going to release version 2.1.0 of apollo-offline and I'll try to integrate this too :)

**Comment by mattjennings** [comment]
awesome, that would be much appreciated!

**Comment by morrys** [comment]
hi @mattjennings,
I just released version 2.1.0 of apollo-offline. 
[Here](
https://github.com/morrys/wora/releases/tag/apollo-offline%402.1.0) you will find details of what has been added and modified.

With this version you can correctly manage all the properties provided by cache-persist.

While [here](https://github.com/morrys/offline-examples/blob/master/apollo/nextjs/apollo/createApolloClient.ts#L40) you can find an example of how to use the indexeddb in nextjs in an SSR context

**Comment by mattjennings** [comment]
thanks for the great work!
