### ISSUE TITLE
Filter mutations in onPublish?

### ISSUE THREAD

**Issue by wilmervanheerde** [morrys/wora#26]
Is there any way to filter mutations out to exclude them from being added to the offline queue? Based on criteria, e.g. a value provided in `context` of a mutation?

**Comment by morrys** [comment]
Hi @wilmervanheerde,
This can be managed in two ways:
* check the network status before executing the mutation (client.isOnline()) and avoid it being executed
* in onPublish based on your criteria throw an error (remember to add the onError option in the mutation

Trying the second mode (which I recommend), there is a small refresh bug (https://github.com/morrys/wora/commit/be9949a9b60274e6bf5106c87d84e970e981319b) which I hope to release this weekend.

**Comment by morrys** [comment]
apollo-offline version 2.1.2 released:
https://github.com/morrys/wora/releases/tag/apollo-offline%402.1.2

**Comment by morrys** [comment]
hi @wilmervanheerde, can I close the issue? :)

**Comment by wilmervanheerde** [comment]
Sure thanks, go ahead
