### ISSUE TITLE
Store mutations offline if server is down / returns error

### ISSUE THREAD

**Issue by mattjennings** [morrys/wora#28]
Using apollo, is there a way to queue the mutation offline if the server cannot be reached ("Failed to fetch" error) or returns a certain error?

**Comment by mattjennings** [comment]
This is currently my (hacky) approach to this:

```ts
  const originalMutate = apolloClient.mutate

  apolloClient.mutate = async options => {
    try {
      const response = await originalMutate(options)

      return response
    } catch (error) {
      if (error.message?.match(/Network error/)) {
        // @ts-ignore - apolloStoreOffline is a private member of apolloClient, but we need access to it to call publish
        return apolloClient.apolloStoreOffline.publish(apolloClient, options)
      }
      throw error
    }
  }
```

which is to mimic what happens in https://github.com/morrys/wora/blob/6bc7c373a8af33814fad0a80bf7e679a599d4cb8/packages/apollo-offline/src/ApolloClientOffline.ts#L84-L90

**Comment by morrys** [comment]
Hi @mattjennings ,
I'm glad to see you always find a workaround :)

At the moment I would tell you to try to directly import the function https://github.com/morrys/wora/blob/master/packages/apollo-offline/src/ApolloStoreOffline.ts#L95.

Now I mark this issue as a feature in order to create a `public mutateOffline(options: any): any` function in the client.

**Comment by mattjennings** [comment]
Hah, yes, thankfully! Thanks for the tip about importing `publish`, that is a bit nicer for the time being!

**Comment by morrys** [comment]
Hi @mattjennings,
yesterday I sketched the changes I will release in the next release: https://github.com/morrys/wora/commit/3af4b1555bbd637f181e8ffe86c0d4b93ec55025

Now I have to test and evaluate further optimizations.

I would like to have your opinion or suggestions :)

**Comment by mattjennings** [comment]
I would suggest being able to pass in a method to the offline store that determines if any mutation should be stored offline based on the error:

```ts
  public mutate<T>(options: MutationOptions): Promise<FetchResult<T>> {
    if (!this.isOnline()) {
      return this.mutateOffline(options)
    }
    return super.mutate(options)
    .catch(error => {
      // shouldPersistOnError would be wherever the onComplete, onDiscard, etc. callbacks are stored
      if (this.getStoreOffline().shouldPersistOnError(error)) {
        return this.mutateOffline(options)
      }
      
      throw error
    })
  }
```

or, maybe `shouldPersistOnError` could return the payload that you want stored, incase it needed further modification. I'm not sure if this is the ideal API, but this would solve my problem.

**Comment by morrys** [comment]
The problem with this solution is conceptual, the management of mutation errors is not pertent with the offline workflow.

For compatibility issues with Apollo, I try to reduce changes to its online behavior as much as possible.


Furthermore, introducing the mutateOffline it is easy for you to manage this requirement with a "mutate" wrapper, right?

it could be the idea of creating this "mutate" wrapper and exposing it as a library utility, what do you say?

**Comment by mattjennings** [comment]
Right, that makes sense. Originally I had thought this solution would work best as an Apollo Link, but to my knowledge you can't access the client or the offline store there (I need to research that some more).

I think exposing the `mutateOffline` method is good though, and maybe that's all someone should need for mutating offline manually. Exposing a mutate wrapper utility function might be worthwhile, too!

**Comment by morrys** [comment]
hi @mattjennings,
version 2.2.0 released! https://github.com/morrys/wora/releases/tag/apollo-offline%402.2.0

Let me know if there are problems, then I will close the issue :)

thanks

**Comment by mattjennings** [comment]
Looks good to me, thanks!
