### ISSUE TITLE
Storage encryption

### ISSUE THREAD

**Issue by richieroldan** [morrys/wora#38]
Hello @morrys !

Thank you for this awesome package!

I just want to ask if you will support storage encryption?
if not, maybe you can give me some insights on how to do it?

Thank you again!

**Comment by morrys** [comment]
hi @richieroldan,
thanks :) can i ask you which libraries are you using?

I can consider to natively integrate the support of Storage encryption in cache-persist and PR are welcome :)

To implement them you need to create a [middleware layer](https://morrys.github.io/wora/docs/cache-persist.html#middleware-layer) similar to [jsonSerialize](https://github.com/morrys/wora/blob/master/packages/cache-persist/src/layers/jsonSerialize.ts):

```ts
import { mutateValuesLayer, IMutateValue } from 'wora/cache-persist';

const encrypt = (value) => todo implementation;

const decrypt = (value) => todo implementation;

const encryptionLayer: IMutateValue = mutateValues((value) => encrypt(JSON.stringify(value)), (value) => decrypt(JSON.parse(value)));

export default encryptionLayer;
```

and finally used in the mutateValues ​​configuration parameter and serialize = false
https://morrys.github.io/wora/docs/cache-persist.html#cache-options

the code is not tested (I wrote it on github), let me know if everything is clear.

**Comment by richieroldan** [comment]
Thank you @morrys for the quick response. 
I'm using apollo-offline btw.
I'll checkout the code first. 

Will close this issue since my question has been answered. Thanks again @morrys !
