### ISSUE TITLE
How to clear IndexedDB

### ISSUE THREAD

**Issue by lochawala** [morrys/wora#62]
How can i clear IndexedDB when user logout or clear existing user data from indexDB and store new login user data?

**Comment by morrys** [comment]
Hi @lochawala,
this should solve your problem
https://www.apollographql.com/docs/react/v2.6/caching/cache-interaction/#resetting-the-store

**Comment by lochawala** [comment]
HI @morrys,
Thanks, It's work's

**Comment by lochawala** [comment]
Hey I have one another question how can i clear indexDB offline store data when it's successfully sync? 
Please check attach screenshot for batter idea 
![Screen Shot 2020-10-20 at 1 00 52 PM](https://user-images.githubusercontent.com/14148438/96554614-63b36500-12d4-11eb-85a5-763bc2cf07a1.png)

**Comment by morrys** [comment]
Hi @lochawala,
I didn't quite understand the question. When offline mutations are performed they are deleted from the offline store.

**Comment by lochawala** [comment]
Hi @morrys 
Yes, it's an expected behaviour but in my case, it's not deleted from an offline store

**Comment by morrys** [comment]
Can you give me your offline options configuration?

**Comment by lochawala** [comment]
`client.setOfflineOptions({
    manualExecution: false, // optional
    link: link, //optional
    start: async (mutations) => { //optional
        console.log("start offline", mutations)
        return mutations;
    },
    finish: async (mutations, error) => { //optional
        console.log("finish offline", error, mutations)
    },
    onExecute: async (mutation) => { //optional
        console.log("onExecute offline", mutation)
        return mutation;
    },
    onComplete: async (options) => { //optional
        console.log("onComplete offline", options)
        onMutationCompleteHandler(client, options.response); // here in this function call client.writeQuery
    },
    onDiscard: async (options) => { //optional
        console.log("onDiscard offline", options)
        return true;
    },
    onPublish: async (offlinePayload) => { //optional
        console.log("offlinePayload", offlinePayload)
        return offlinePayload
    }
});`

**Comment by morrys** [comment]
The problem is in onComplete function. You must return true to delete mutation in offline store :)

**Comment by lochawala** [comment]
Oh yes 
Thanks @morrys for pointing me out now it's work's
