### ISSUE TITLE
Support relay-runtime v10.1.x

### ISSUE THREAD

**Issue by JonathanUsername** [morrys/wora#64]
https://github.com/morrys/wora/blob/master/packages/relay-store/src/Store.ts#L91
This line is failing on the latest version of relay (10.1.0).

I think it's due to this rename. More info here:
https://github.com/facebook/relay/issues/3165

Current workaround that works and so enhances my suspicions:
```javascript
import { Store } from 'react-relay-offline';

Store.prototype._scheduleGC = Store.prototype.scheduleGC
```

**Comment by morrys** [comment]
@JonathanUsername, 
I am working on relay v10.1 support for react-relay-offline, wora/relay-offline & wora/relay-store.

more info:
https://github.com/relay-tools/relay-hooks/issues/126
https://github.com/morrys/react-relay-offline/issues/55

**Comment by morrys** [comment]
branch: https://github.com/morrys/wora/tree/support-relay-10
