### ISSUE TITLE
error: when I'm trying to perform a mutation without optimistic response whilst offline

### ISSUE THREAD

**Issue by morrys** [morrys/wora#7]
@morrys Thanks that worked!

However now when I'm trying to perform a mutation whilst offline, I get this error:
```js
TypeError: Cannot read property 'updateUser' of undefined
    at bundle.esm.js:605
    at Array.forEach (<anonymous>)
    at StoreWriter../node_modules/apollo-cache-inmemory/lib/bundle.esm.js.StoreWriter.writeSelectionSetToStore (bundle.esm.js:599)
    at StoreWriter../node_modules/apollo-cache-inmemory/lib/bundle.esm.js.StoreWriter.writeResultToStore (bundle.esm.js:577)
    at ApolloCache../node_modules/apollo-cache-inmemory/lib/bundle.esm.js.InMemoryCache.write (bundle.esm.js:913)
    at bundle.esm.js:1866
    at Array.forEach (<anonymous>)
    at bundle.esm.js:1866
    at ApolloCache../node_modules/apollo-cache-inmemory/lib/bundle.esm.js.InMemoryCache.performTransaction (bundle.esm.js:979)
    at DataStore../node_modules/apollo-client/bundle.esm.js.DataStore.markMutationResult (bundle.esm.js:1865)
```

_Originally posted by @harveyconnor in https://github.com/morrys/wora/issues/4#issuecomment-513608162_

**Comment by morrys** [comment]
Hi @harveyconnor,
for this error I opened this new issue:

with this log it is difficult to go back to the cause of the error, can you give me some more information?

* mutation code
* Has the mutation data persisted in the offline cache?
* Have you tried other mutations?

Thank you,
Lorenzo

**Comment by harveyconnor** [comment]
updateUser mutation:
```gql
  mutation updateUser(
    $id: ID!
    $firstName: String
    $lastName: String
    $email: String
    $password: String
  ) {
    updateUser(
      id: $id
      firstName: $firstName
      lastName: $lastName
      email: $email
      password: $password
    ) {
      id
      email
      firstName
      lastName
      updatedAt
      createdAt
    }
  }
```

No the data has not been persisted.

I have tried others and still the same issue.

**Comment by morrys** [comment]
I meant the code of the react-apollo mutation, are you using the optimistic responses?

**Comment by harveyconnor** [comment]
```ts
updateUser = () => {
    this.props.updateUser({
      variables: {
        id: this.props.user.id,
        ...variables,
      },
    })
      .then(() => {
        console.log('updated User!');
      })
      .catch(console.error);
  };
```
This works fine whilst online. 
And no I'm not performing optimistic responses, do I need to?

**Comment by morrys** [comment]
in these early versions of the library it is **necessary** to use the **optimistic response**, to ensure that anyone who uses this library understands its importance in the offline context.

A correct use of optimistic response and the update function ensures **greater control and integrity of the cache** and a **better user experience**

If there is a real need not to use the optimistic response, we can discuss this and evaluate its implementation

Another useful **requirement** to guarantee **consistency and efficiency** is **the generation of identifiers** of new entities in the **client and not in the server**

I will add this information to the README.md

I would like to know your opinion.

Thank you,
Lorenzo

**Comment by harveyconnor** [comment]
Ahhh okay. That makes sense. I was more so thinking it requires more code.
That definitely sounds better.

**Comment by morrys** [comment]
I leave the issue open to give greater visibility to the topic.

Let me know if you have problems with optimistic responses.

**Comment by morrys** [comment]
With the new release it is possible to make mutations offline without using the optimistic response.
https://github.com/morrys/wora/releases/tag/apollo-offline%402.4.0

Its use case is expected when:
   * there are offline mutations that do not make changes in the store
   * you intend to manage the cache update in the onComplete callback as described in this article: https://dev.to/willsamu/how-to-get-aws-appsync-running-with-offline-support-and-react-hooks-678

the second use case is only recommended for managing applications that are offline for a short period of time.
