### ISSUE TITLE
RESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by wewebdeveloper** [morrys/wora#79]
getting below error

React Version: 17.0.2
node Version: 14.15.4
npm  Version: 7.5.3

![error image](https://user-images.githubusercontent.com/79635747/112124778-bdec8500-8be8-11eb-8730-e4c331262424.png)

My package.json file dependencies

![Screenshot 2021-03-23 at 3 03 42 PM](https://user-images.githubusercontent.com/79635747/112125027-00ae5d00-8be9-11eb-850f-f6aeb810df01.png)

**Comment by morrys** [comment]
Hi @wewebdeveloper,
to install wora/apollo-offline you also need to install these dependencies (in the library they are considered peerDependencies): https://github.com/morrys/wora/blob/master/packages/apollo-offline/package.json#L43

**Comment by wewebdeveloper** [comment]
Hi @morrys 

Thanks, it's working fine now
